### ISSUE TITLE
when trying to connect it show me this error

### ISSUE THREAD

**Issue by Zeeshan-The-Dev** [shadowsocksRb/shadowsocksRb-android#4]
io.github.shadowsocksrb.debug E/shadowsocksRb: Crashlytics logException:
    java.io.IOException: Cannot run program "/data/app/io.github.shadowsocksrb.debug-GBr4C2ACugx4MEgCUqzHzg==/lib/arm64/libss-local.so" (in directory "/data/user_de/0/io.github.shadowsocksrb.debug/no_backup"): error=2, No such file or directory

**Comment by myflyingfish** [comment]
same error when use app bundle

**Comment by shadowsocksRb** [comment]
As a developer, you should solve this problem yourself.
