### ISSUE TITLE
这个客户端的耗电量有点大，能不能对此优化一下...

### ISSUE THREAD

**Issue by DogeNeko** [shadowsocksRb/shadowsocksRb-android#5]
我的手机耗电显示，在四个小时内，屏幕耗电是28.48%，ssr有37.61%之多。耗电量有些大，手机续航有些撑不住

**Comment by zhaoweih** [comment]
@007-jqm 可以 在配置里头 设置 **分应用VPN功能**，仅允许需要翻墙的应用经过ssr

**Comment by shadowsocksRb** [comment]
阅读常见问题
