### ISSUE TITLE
你好怎么编译啊？

### ISSUE THREAD

**Issue by baodp** [shadowsocksRb/shadowsocksRb-android#6]
./gradlew aR
输入 win11 ubuntu  显示如下：

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':core'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/home/bdp/shadowsocksRb-android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 496ms

**Comment by ikebo** [comment]
我是mac环境下编译的，下载相关Android SDK 和 NDK 和 gradle. 然后 ./gradlew aR 可以编译成功

**Comment by zhaowhao** [comment]
https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil

 在根目录增加`local.properties`文件 配置`sdk.dir=PATH/TO/YOUR/SDK ` 后面是你的sdk目录
